const issues=[
{t:'Detector interaction',b:'One stage changes the conditions the next stage uses to decide.',c:'An upstream processor changes spectral energy in a region that a downstream detector is also watching.',s:'Pumping, inconsistent cleanup, or processors that seem to fight.',a:'Assign distinct roles and reduce overlap. If two stages must watch the same region, keep at least one gentle.'},
{t:'Overlapping reduction',b:'Several small cuts become one large cut.',c:'Multiple processors attenuate the same bins or bands.',s:'Hollow timbre, missing consonants, or over-thinned speech.',a:'Inspect cumulative attenuation and divide responsibility by problem type.'},
{t:'Envelope uulation',b:'Different recovery behaviors combine into a moving texture.',c:'Plugins use different attacks, releases, FFT windows, or gate recovery over related content.',s:'Wavering background, watery motion, flutter, or unstable ambience.',a:'Coordinate time behavior and avoid broad moving masks piled onto the same material.'},
{t:'Noise-floor modulation',b:'The background opens and closes around speech.',c:'Thresholded stages trigger and recover differently.',s:'Breathing, chattering, or obvious room-noise pumping.',a:'Use gentler recovery, fewer thresholded stages, and avoid several hard gates at once.'},
{t:'Transient loss',b:'Fast events are mistaken for disposable noise.',c:'Long windows or slow detectors smooth over brief consonants and transient details.',s:'Dull articulation, softened attacks, reduced intelligibility.',a:'Handle impulsive contamination early with faster tools; let slower stages address slower-changing noise.'},
{t:'Mask chasing',b:'Later stages learn earlier artifacts as though they were the new noise.',c:'Repeated denoise → reconstruct → reanalyze cycles.',s:'Metallic residue, recursive grit, or a processed-the-processing quality.',a:'Analyze the original source where possible, or specialize each serial stage narrowly.'},
{t:'Crossover conflict',b:'Band boundaries and targeted control interfere.',c:'Dynamic EQ, de-essing, and multiband compression all work around the same crossover region.',s:'Tonal shifting or frequency-dependent instability.',a:'Use broad macro control in one layer and surgical exceptions in another.'},
{t:'Latency / phase mismatch',b:'Parallel branches stop lining up.',c:'Different FFT, lookahead, crossover, or plug-in latencies are recombined.',s:'Comb filtering, hollowing, or image smear.',a:'Use delay compensation, confirm alignment, and avoid casual parallel recombination of unlike structures.'},
{t:'Gain-staging drift',b:'The next detector receives a biased input.',c:'An upstream stage changes level or spectral balance enough to alter downstream triggering.',s:'Over-triggering or inconsistent thresholds.',a:'Level-match between stages and make pre-detector boosts intentional.'}
];
const btns=document.getElementById('issueButtons'),detail=document.getElementById('issueDetail');
function showIssue(i){[...btns.children].forEach((b,n)=>b.classList.toggle('active',n===i));const x=issues[i];detail.innerHTML=`<h3>${x.t}</h3><p>${x.b}</p><dl><dt>Cause</dt><dd>${x.c}</dd><dt>What it sounds like</dt><dd>${x.s}</dd><dt>How to avoid it</dt><dd>${x.a}</dd></dl>`}
issues.forEach((x,i)=>{const b=document.createElement('button');b.innerHTML=`<b>${x.t}</b><small>${x.b}</small>`;b.onclick=()=>showIssue(i);btns.appendChild(b)});showIssue(0);

const fft=document.getElementById('fftSlider'),fftSvg=document.getElementById('fftSvg');
function word(v){return v>.78?'Very high':v>.58?'High':v>.38?'Moderate':v>.18?'Low':'Very low'}
function fit(ms){return ms<=12?'Impulses / clicks':ms<=35?'General speech denoise':ms<=70?'Broad cleanup + tonal separation':'Steady tonal residue'}
function drawFFT(){const ms=+fft.value,t=Math.max(.05,1-(ms-5)/115),f=Math.max(.05,(ms-5)/115);fftValue.textContent=ms;transientScore.textContent=word(t);frequencyScore.textContent=word(f);bestFit.textContent=fit(ms);fftNarrative.textContent=ms<=12?'Fast and temporally precise, but spectrally coarse.':ms<=35?'A useful speech compromise between timing and frequency detail.':ms<=70?'More frequency detail with greater temporal smearing.':'Strongly frequency-selective; best for steady contamination rather than fast speech events.';let pt='',pf='';for(let i=0;i<=115;i++){let x=62+i/115*560,tt=Math.max(.05,1-i/115),ff=Math.max(.05,i/115),yt=228-tt*170,yf=228-ff*170;pt+=`${i?'L':'M'} ${x} ${yt} `;pf+=`${i?'L':'M'} ${x} ${yf} `}let x=62+(ms-5)/115*560;fftSvg.innerHTML=`<rect width="700" height="300" rx="20" fill="rgba(255,255,255,.02)"/><g stroke="rgba(255,255,255,.1)"><line x1="62" y1="228" x2="622" y2="228"/><line x1="62" y1="58" x2="62" y2="228"/></g><path d="${pt}" stroke="#72f0d3" stroke-width="4" fill="none"/><path d="${pf}" stroke="#6bc0ff" stroke-width="4" fill="none"/><line x1="${x}" y1="58" x2="${x}" y2="228" stroke="#fff" stroke-opacity=".28" stroke-dasharray="6 6"/><text x="70" y="42" fill="#72f0d3" font-size="14" font-weight="700">Temporal precision</text><text x="260" y="42" fill="#6bc0ff" font-size="14" font-weight="700">Frequency specificity</text><text x="60" y="252" fill="#a9bdd2" font-size="12">5 ms</text><text x="590" y="252" fill="#a9bdd2" font-size="12">120 ms</text>`}
fft.oninput=drawFFT;drawFFT();

const d=[db1,db2,db3];function gain(db){return Math.pow(10,-db/20)}function drawAtt(){let v=d.map(x=>+x.value),td=v.reduce((a,b)=>a+b,0),p=v.reduce((a,b)=>a*gain(b),1);dbTotal.textContent=`Total attenuation: ${td.toFixed(1)} dB`;ampTotal.textContent=`Remaining amplitude: ${(p*100).toFixed(1)}%`;let colors=['#72f0d3','#6bc0ff','#ffd36b'];attenSvg.innerHTML=`<rect width="760" height="190" rx="20" fill="rgba(255,255,255,.02)"/><text x="30" y="34" fill="#eef6ff" font-size="16" font-weight="700">Serial reductions accumulate</text>${v.map((db,i)=>{let x=34+i*230,g=gain(db);return `<text x="${x}" y="64" fill="#a9bdd2" font-size="13">Stage ${i+1}: −${db.toFixed(1)} dB</text><rect x="${x}" y="82" width="180" height="24" rx="12" fill="rgba(255,255,255,.06)"/><rect x="${x}" y="82" width="${180*g}" height="24" rx="12" fill="${colors[i]}"/><text x="${x}" y="128" fill="#eef6ff" font-size="12">Stage gain: ${(g*100).toFixed(1)}%</text>`}).join('')}<text x="520" y="163" fill="#72f0d3" font-size="15" font-weight="700">Final amplitude ${(p*100).toFixed(1)}%</text>`}d.forEach(x=>x.oninput=drawAtt);drawAtt();

const rs=[rel1,rel2,rel3];function assess(v){let s=[...v].sort((a,b)=>a-b),r=s[2]/s[0];return r<1.6?'These release times are fairly coordinated.':r<3.5?'Moderate mismatch: watch for moving background texture.':'Strong mismatch: higher risk of flutter, breathing, and envelope uulation.'}function drawRel(){let v=rs.map(x=>+x.value);releaseSummary.textContent=assess(v);let colors=['#72f0d3','#6bc0ff','#ffd36b'],paths=v.map(ms=>{let p='';for(let i=0;i<=100;i++){let n=i/100,y=Math.exp(-n/Math.max(.12,ms/220)),x=50+n*660,yy=210-y*150;p+=`${i?'L':'M'} ${x} ${yy} `}return p});releaseSvg.innerHTML=`<rect width="760" height="250" rx="20" fill="rgba(255,255,255,.02)"/><g stroke="rgba(255,255,255,.1)"><line x1="50" y1="210" x2="710" y2="210"/><line x1="50" y1="60" x2="50" y2="210"/></g>${paths.map((p,i)=>`<path d="${p}" stroke="${colors[i]}" stroke-width="3" fill="none"/><text x="${55+i*165}" y="45" fill="${colors[i]}" font-size="13">Stage ${i+1}: ${v[i]} ms</text>`).join('')}`}rs.forEach(x=>x.oninput=drawRel);drawRel();

let mode='bad';const chainSvg=document.getElementById('chainSvg'),chainText=document.getElementById('chainText'),modes=[...document.querySelectorAll('[data-mode]')];function box(x,y,w,h,t,fill='rgba(255,255,255,.05)'){return `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="16" fill="${fill}" stroke="rgba(255,255,255,.18)"/><text x="${x+w/2}" y="${y+h/2+5}" fill="#eef6ff" font-size="14" text-anchor="middle">${t}</text>`}function renderChain(){modes.forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));if(mode==='bad'){chainSvg.innerHTML=`${box(30,132,110,70,'Input')}${box(180,132,170,70,'General denoise')}${box(390,132,170,70,'General denoise')}${box(600,132,170,70,'General denoise')}${box(800,132,90,70,'Out')}<text x="460" y="55" fill="#eef6ff" font-size="18" text-anchor="middle">Too much overlapping authority</text>`;chainText.innerHTML='<h3>Bad pattern</h3><p>Several stages all answer the same question: “remove noise in general.” Later stages analyze earlier artifacts, reductions overlap, and recovery behavior diverges.</p>'}else if(mode==='good'){chainSvg.innerHTML=`${box(30,132,110,70,'Input')}${box(165,132,170,70,'Short-event cleanup')}${box(365,132,170,70,'Main denoise')}${box(565,132,170,70,'Tonal cleanup')}${box(765,132,125,70,'Dyn EQ / de-ess')}<text x="460" y="55" fill="#eef6ff" font-size="18" text-anchor="middle">Each stage is a specialist</text>`;chainText.innerHTML='<h3>Safer default</h3><p>Each stage solves a distinct problem. The chain reads like separate responsibilities rather than repeated guesses at the same responsibility.</p>'}else{chainSvg.innerHTML=`${box(30,135,120,70,'Original input')}${box(220,42,160,56,'Short analysis')}${box(220,142,160,56,'Medium analysis')}${box(220,242,160,56,'Long analysis')}${box(470,142,170,70,'Mask fusion','rgba(107,192,255,.12)')}${box(720,142,150,70,'One final gain field','rgba(114,240,211,.12)')}<text x="460" y="26" fill="#eef6ff" font-size="18" text-anchor="middle">Several analyses, one coherent modification</text>`;chainText.innerHTML='<h3>Cleaner architecture</h3><p>Multiple resolutions analyze the same original material, then their decisions are combined before one final modification. This reduces mask chasing and repeated reconstruction artifacts.</p>'}}modes.forEach(b=>b.onclick=()=>{mode=b.dataset.mode;renderChain()});renderChain();
